Repository jenkins-x-plugins/jx-promote, pull requests merged in 2020-12, with the labels that each got.

#158 refactor: remove old v2 requirements
  go.mod
  go.sum
  jx/bdd/boot-lh-ghe/jx-requirements.yml
  jx/bdd/boot-vault/jx-requirements.yml
  pkg/envctx/env_context.go
  pkg/envctx/load.go
  pkg/environments/types.go
  pkg/jxtesthelpers/jx_resources.go
  pkg/promote/pr.go
  pkg/promote/promote.go
  pkg/promote/promote_integration_test.go
  pkg/promote/promote_test.go
  pkg/rules/factory/test_data/helmfile-explicit/helmfile.yaml.1.expected
  pkg/rules/factory/test_data/helmfile-explicit/helmfile.yaml.2.expected
  pkg/rules/factory/test_data/helmfile-new-repository/helmfile.yaml.1.expected
  pkg/rules/factory/test_data/helmfile-new-repository/helmfile.yaml.2.expected
  pkg/rules/factory/test_data/helmfile/helmfile.yaml.1.expected
  pkg/rules/factory/test_data/helmfile/helmfile.yaml.2.expected
Labels: approved, size/XL

#162 refactor: move traditional CRDs back to jenkins.io group so we dont n…
  go.mod
  go.sum
  pkg/envctx/env_context.go
  pkg/envctx/load.go
  pkg/jxtesthelpers/jx_resources.go
  pkg/promote/pr.go
  pkg/promote/promote.go
  pkg/promote/promote_integration_test.go
  pkg/promote/promote_test.go
Labels: approved, size/M

#168 chore: upgrade pipelines
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: size/M, updatebot

#172 fix: switch to multi-arch catalog
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/M

#173 fix: upgrade pipeline
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/release.yaml
Labels: size/S

#174 refactor: lets use the new jx-helper GetClusterRequirementsConfig function
  go.mod
  go.sum
  pkg/envctx/load.go
  pkg/jxtesthelpers/jx_resources.go
  pkg/promote/promote.go
  pkg/promote/promote_integration_test.go
Labels: approved

#176 fix: lets support nested helmfiles in promote
  go.mod
  go.sum
  pkg/promoteconfig/helpers.go
  pkg/rules/factory/factory_test.go
  pkg/rules/factory/test_data/helmfile-nested/helmfile.yaml
  pkg/rules/factory/test_data/helmfile-nested/helmfile.yaml.expected
  pkg/rules/factory/test_data/helmfile-nested/helmfiles/jx/helmfile.yaml.1.expected
  pkg/rules/factory/test_data/helmfile-nested/helmfiles/jx/helmfile.yaml.2.expected
  pkg/rules/factory/test_data/helmfile-nested/helmfiles/nginx/helmfile.yaml
  pkg/rules/helmfile/helmfile_rule.go
Labels: approved, size/L

#188 fix: upgrade promote in jx-cli on release
  .jx/updatebot.yaml
Labels: approved, size/XS

#197 chore: tone down debugging
  pkg/environments/gitops.go
Labels: approved, size/XS

#200 fix: upgrade deps
  go.mod
  go.sum
  pkg/promote/promote.go
  pkg/rules/factory/test_data/helmfile-explicit/helmfile.yaml.1.expected
  pkg/rules/factory/test_data/helmfile-explicit/helmfile.yaml.2.expected
  pkg/rules/factory/test_data/helmfile-nested/helmfile.yaml.expected
  pkg/rules/factory/test_data/helmfile-nested/helmfiles/jx/helmfile.yaml.1.expected
  pkg/rules/factory/test_data/helmfile-nested/helmfiles/jx/helmfile.yaml.2.expected
  pkg/rules/factory/test_data/helmfile-new-repository/helmfile.yaml.1.expected
  pkg/rules/factory/test_data/helmfile-new-repository/helmfile.yaml.2.expected
  pkg/rules/factory/test_data/helmfile/helmfile.yaml.1.expected
  pkg/rules/factory/test_data/helmfile/helmfile.yaml.2.expected
Labels: approved, size/M
