Repository jenkins-x-plugins/jx-promote, pull requests merged in 2020-09, with the labels that each got.

#46 fix: upgrade deps
  go.mod
  go.sum
Labels: size/S

#48 feat: Add promotion environments
  pkg/cmd/root.go
  pkg/promote/promote.go
Labels: approved, ok-to-test, size/S

#49 fix: lets default to use the dev environment
  go.mod
  go.sum
  pkg/envctx/load.go
Labels: approved, size/M

#50 fix: add the git user/token when cloning the development git repo
  pkg/envctx/env_context.go
  pkg/envctx/load.go
Labels: approved, size/M

#53 fix: removed the old jx-apps logic
  go.mod
  go.sum
  pkg/apis/promote/v1alpha1/types.go
  pkg/envctx/env_context.go
  pkg/envctx/env_context_test.go
  pkg/environments/gitops.go
  pkg/environments/types.go
  pkg/promote/pr.go
  pkg/promote/promote_integration_test.go
  pkg/promoteconfig/helpers.go
  pkg/rules/apps/apps_rule.go
  pkg/rules/factory/factory.go
  pkg/rules/factory/factory_test.go
  pkg/rules/factory/test_data/jx-apps-empty/jx-apps.yml
  pkg/rules/factory/test_data/jx-apps-empty/jx-apps.yml.1.expected
  pkg/rules/factory/test_data/jx-apps-empty/jx-apps.yml.2.expected
  pkg/rules/factory/test_data/jx-apps-explicit/.jx/promote.yaml
  pkg/rules/factory/test_data/jx-apps-explicit/jx-apps.yml
  pkg/rules/factory/test_data/jx-apps-explicit/jx-apps.yml.1.expected
  pkg/rules/factory/test_data/jx-apps-explicit/jx-apps.yml.2.expected
  pkg/rules/factory/test_data/jx-apps-new-repository/jx-apps.yml
  pkg/rules/factory/test_data/jx-apps-new-repository/jx-apps.yml.1.expected
  pkg/rules/factory/test_data/jx-apps-new-repository/jx-apps.yml.2.expected
  pkg/rules/factory/test_data/jx-apps/jx-apps.yml
  pkg/rules/factory/test_data/jx-apps/jx-apps.yml.1.expected
  pkg/rules/factory/test_data/jx-apps/jx-apps.yml.2.expected
  pkg/rules/kpt/kpt_rule.go
Labels: approved, size/XXL

#55 feat: add default app namespace
  pkg/cmd/root.go
  pkg/promote/pr.go
  pkg/promote/promote.go
  pkg/rules/helmfile/helmfile_rule.go
  pkg/rules/helmfile/helpers.go
Labels: approved, ok-to-test, size/M

#57 fix: allow labels to be added to PRs
  go.mod
  go.sum
  pkg/common/helpers.go
  pkg/envctx/env_context.go
  pkg/envctx/load.go
  pkg/environments/gitops.go
  pkg/environments/pr.go
  pkg/rules/factory/factory.go
  pkg/rules/file/file_rule.go
  pkg/rules/helm/helm_rule.go
  pkg/rules/helmfile/helmfile_rule.go
  pkg/rules/kpt/kpt_rule.go
Labels: approved, size/XL

#58 fix: avoid creating a new ScmClient in unit tests
  go.mod
  go.sum
  pkg/environments/gitops.go
  pkg/environments/pr.go
  pkg/environments/types.go
Labels: approved, size/L

#59 fix: adding labels properly on quickstarts
  pkg/environments/gitops.go
Labels: approved, size/S

#61 fix: use canonical output so we don't break the BDD tests
  go.mod
  go.sum
  pkg/environments/pr.go
Labels: approved, size/S

#62 fix: upgrade deps
  go.mod
  go.sum
Labels: approved, size/S

#64 fix: upgrade deps and docs
  docs/cmd/jx-promote.md
  docs/config.md
  docs/man/man1/jx-promote.1
  go.mod
  go.sum
Labels: approved, size/L

#65 fix: improve the promote commit message
  pkg/promote/pr.go
  pkg/promote/promote.go
Labels: approved, size/M

#66 fix: detect the version from the VERSION file
  go.mod
  go.sum
  pkg/promote/promote.go
Labels: approved, size/L

#68 fix: lets not add the auto merge label if draftPR
  pkg/promote/pr.go
Labels: approved, size/S

#69 fix: for multiple promote environments
  pkg/promote/promote.go
Labels: approved, size/XS

#75 fix: add do not merge label for draft PRs
  go.mod
  go.sum
  pkg/promote/pr.go
Labels: approved, size/S

#76 fix: if not polling for promote PR status, mark PA as complete
  go.mod
  go.sum
  pkg/promote/promote.go
  pkg/promote/promote_integration_test.go
Labels: approved, size/M

#79 fix: use correct branch name when creating/updating the PipelineActivity
  go.mod
  go.sum
  pkg/promote/promote.go
Labels: approved, size/S

#81 fix: lazy discover the git kind
  go.mod
  go.sum
  pkg/environments/pr.go
  pkg/environments/types.go
Labels: approved, size/M
