Repository jenkins-x-plugins/jx-promote, pull requests merged in 2020-10, with the labels that each got.

#83 fix: better PR title
  pkg/promote/pr.go
Labels: approved, lgtm, ok-to-test, size/XS

#86 chore: upgrade and align with kubernetes dependencies 0.19.2, also update to go 1.15
  go.mod
  go.sum
  jenkins-x.yml
  pkg/cmd/root.go
  pkg/envctx/env_context.go
  pkg/envctx/load.go
  pkg/environments/gitops.go
  pkg/environments/pr.go
  pkg/environments/types.go
  pkg/jxtesthelpers/jx_resources.go
  pkg/promote/pr.go
  pkg/promote/promote.go
  pkg/promote/promote_integration_test.go
  pkg/promote/promote_test.go
  pkg/promoteconfig/helpers.go
  pkg/rules/factory/factory_test.go
  pkg/rules/file/file_rule.go
  pkg/rules/helm/helm_rule.go
  pkg/rules/helmfile/helmfile_rule.go
  pkg/rules/helmfile/helpers.go
  pkg/rules/kpt/kpt_rule.go
  pkg/rules/types.go
Labels: approved, lgtm, size/XL

#95 fix: lets use the git username and token when cloning
  go.mod
  go.sum
  pkg/environments/gitops.go
Labels: approved, size/M

#97 fix: use a quiet command runner by default
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  .lighthouse/jenkins-x/triggers.yaml
  go.mod
  go.sum
  jenkins-x.yml
  pkg/environments/pr.go
Labels: size/XL

#115 fix: lets disable automatic merge by default
  go.mod
  go.sum
  pkg/promote/pr.go
  pkg/promote/promote.go
Labels: approved, size/S
