Repository jenkins-x-plugins/jx-promote, pull requests merged in 2021-06, with the labels that each got.

#377 chore: fix spelling mistake
  pkg/envctx/load.go
Labels: approved, lgtm, ok-to-test, size/XS

#378 fix: trim * from any ingress URLs
  go.mod
  go.sum
  pkg/promote/promote.go
  pkg/promote/promote_integration_test.go
Labels: approved, size/M

#379 fix: upgrade deps
  go.mod
  go.sum
Labels: approved, size/S
