Repository jenkins-x-plugins/jx-promote, pull requests merged in 2021-01, with the labels that each got.

#202 Helmfile keep old releases
  .gitignore
  pkg/apis/promote/v1alpha1/types.go
  pkg/rules/factory/factory_test.go
  pkg/rules/factory/test_data/helmfile-explicit-keep-old-releases/.jx/promote.yaml
  pkg/rules/factory/test_data/helmfile-explicit-keep-old-releases/helmfile.yaml
  pkg/rules/factory/test_data/helmfile-explicit-keep-old-releases/helmfile.yaml.1.expected
  pkg/rules/factory/test_data/helmfile-explicit-keep-old-releases/helmfile.yaml.2.expected
  pkg/rules/factory/test_data/helmfile-nested-explicit-keep-old-releases/.jx/promote.yaml
  pkg/rules/factory/test_data/helmfile-nested-explicit-keep-old-releases/helmfile.yaml
  pkg/rules/factory/test_data/helmfile-nested-explicit-keep-old-releases/helmfile.yaml.expected
  pkg/rules/factory/test_data/helmfile-nested-explicit-keep-old-releases/helmfiles/jx/helmfile.yaml.1.expected
  pkg/rules/factory/test_data/helmfile-nested-explicit-keep-old-releases/helmfiles/jx/helmfile.yaml.2.expected
  pkg/rules/factory/test_data/helmfile-nested-explicit-keep-old-releases/helmfiles/nginx/helmfile.yaml
  pkg/rules/helmfile/helmfile_rule.go
Labels: approved, lgtm, ok-to-test, size/L

#153 fix: Promote to multiple Auto remote environments
  pkg/environments/gitops.go
  pkg/promote/pr.go
  pkg/promote/promote.go
  pkg/rules/helmfile/helmfile_rule.go
Labels: approved, lgtm, ok-to-test, size/M

#215 fix: lets add an --all mode for promotion
  go.mod
  go.sum
  pkg/cmd/root.go
  pkg/promote/promote.go
  pkg/promote/promote_integration_test.go
Labels: approved, size/L

#216 fix: group Auto promotions on same git repo to same PR
  docs/config.md
  go.mod
  go.sum
  pkg/promote/pr.go
  pkg/promote/promote.go
  pkg/promote/promote_integration_test.go
Labels: approved, size/XL

#217 chore: Remove envNames from promote commit message
  pkg/promote/pr.go
Labels: approved, lgtm, ok-to-test, size/XS

#231 chore: upgrade deps
  go.mod
  go.sum
Labels: approved, size/M

#236 fix: switch promote to use git config
  go.mod
  go.sum
  pkg/envctx/load.go
  pkg/promote/pr.go
  pkg/promote/promote.go
  pkg/promote/promote_integration_test.go
  pkg/promote/promote_test.go
Labels: approved, size/XL

#237 fix: add a default promotion strategy if its missing
  pkg/promote/promote.go
Labels: approved, size/XS

#239 fix: handle the dev git repo changing locally
  go.mod
  go.sum
  pkg/envctx/load.go
Labels: approved

#241 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: size/XS, updatebot

#242 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: size/XS, updatebot

#243 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: updatebot

#245 fix: upgrade dependencies
  go.mod
  go.sum
  pkg/environments/gitops.go
  pkg/environments/types.go
Labels: approved, size/L

#246 fix: avoid reusing forks
  pkg/environments/gitops.go
Labels: approved

#247 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: size/M, updatebot

#251 chore: upgrade deps
  go.mod
  go.sum
Labels: approved, size/XL

#252 fix: handle promote with github pages chart repos
  pkg/promote/promote.go
  pkg/promote/promote_integration_test.go
  pkg/promote/promote_test.go
  pkg/promote/test_data/ghpages/.jx/settings.yaml
  pkg/promote/test_data/ghpages/VERSION
Labels: approved

#266 chore: upgrade deps
  go.mod
  go.sum
  pkg/promote/pr.go
Labels: approved, size/M

#265 chore: upgrade pipelines
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/L, updatebot

#267 chore: try bigger CPU and disk
  .lighthouse/jenkins-x/release.yaml
  cloudbuild.yaml
  go.mod
  go.sum
  pkg/promote/promote_integration_test.go
Labels: approved, size/M

#268 chore: try fix release pipeline
  .lighthouse/jenkins-x/release.yaml
  cloudbuild.yaml
  go.mod
  go.sum
Labels: size/S

#269 chore: lets do arm64 first
  .goreleaser.yml
  cloudbuild.yaml
  promote.sh
Labels: size/S

#270 chore: add a github action
  .github/workflows/imaegs.yaml
Labels: size/M

#273 chore: upgrade helmfile dep
  go.mod
  go.sum
Labels: approved, lgtm, ok-to-test, size/S

#264 fix: dont always override namespace
  pkg/rules/helmfile/helmfile_rule.go
Labels: approved, lgtm, ok-to-test, size/S
