Repository jenkins-x-plugins/jx-promote, pull requests merged in 2021-03, with the labels that each got.

#329 fix: bug when trying to promote to a named local env
  go.mod
  go.sum
  pkg/promote/pr.go
  pkg/promote/promote_integration_test.go
Labels: approved, size/L

#331 fix: upgrade deps
  go.mod
  go.sum
Labels: approved, size/S

#339 chore: upgrade deps
  go.mod
  go.sum
Labels: approved, size/S

#344 chore: upgrade deps
  docs/cmd/promote.md
  docs/config.md
  docs/man/man1/promote.1
  go.mod
  go.sum
Labels: approved, size/L

#346 fix: lets prefer to promote with the public chart repository URL
  pkg/promote/promote.go
  pkg/promote/promote_integration_test.go
Labels: approved, size/L

#347 fix: improve the remote chart repository detection
  pkg/promote/promote.go
  pkg/promote/promote_integration_test.go
  pkg/promote/promote_test.go
Labels: approved, size/M

#348 fix: upgrade deps
  go.mod
  go.sum
  pkg/envctx/env_context.go
  pkg/envctx/load.go
Labels: approved, size/S

#352 fix: set the OCI flag if promoting to an OCI repository
  go.mod
  go.sum
  pkg/envctx/load.go
  pkg/promote/pr.go
  pkg/promote/promote_integration_test.go
  pkg/promote/promote_test.go
  pkg/rules/helmfile/helmfile_rule.go
Labels: approved, size/L

#355 chore: move to plugins org
  .goreleaser.yml
  .jx/updatebot.yaml
  Makefile
  README.md
  cmd/app/main-win.go
  cmd/app/main.go
  cmd/docs/main.go
  cmd/main.go
  go.mod
  go.sum
  hack/changelog-header.md
  pkg/cmd/root.go
  pkg/envctx/load.go
  pkg/environments/types.go
  pkg/jxtesthelpers/jx_resources.go
  pkg/promote/pr.go
  pkg/promote/promote.go
  pkg/promote/promote_integration_test.go
  pkg/promote/promote_test.go
  pkg/promoteconfig/helpers.go
  pkg/promoteconfig/helpers_test.go
  pkg/rules/factory/factory.go
  pkg/rules/factory/factory_test.go
  pkg/rules/file/file_rule.go
  pkg/rules/helm/helm_rule.go
  pkg/rules/helmfile/helmfile_rule.go
  pkg/rules/kpt/kpt_rule.go
  pkg/rules/types.go
Labels: approved, size/L
