Repository jenkins-x-plugins/jx-promote, pull requests merged in 2021-04, with the labels that each got.

#356 chore: upgrade deps
  go.mod
  go.sum
Labels: approved, size/M

#357 fix: add retry around looking up the PullRequest
  go.mod
  go.sum
  pkg/environments/pr.go
  pkg/environments/types.go
  pkg/jxtesthelpers/jx_resources.go
  pkg/promote/pr.go
  pkg/promote/promote.go
  pkg/promote/promote_integration_test.go
  pkg/promote/promote_test.go
  pkg/promoteconfig/helpers.go
  pkg/rules/factory/factory_test.go
  pkg/rules/file/file_rule.go
  pkg/rules/helm/helm_rule.go
  pkg/rules/helmfile/helmfile_rule.go
  pkg/rules/kpt/kpt_rule.go
  pkg/rules/types.go
Labels: approved, size/M

#358 fix: updatebot
  .jx/updatebot.yaml
Labels: approved, size/XS

#360 chore: upgrade deps
  go.mod
  go.sum
Labels: approved, size/S

#361 chore: upgrade deps
  docs/cmd/promote.md
  docs/config.md
  go.mod
  go.sum
Labels: approved, size/M

#362 chore: upgrade deps
  README.md
  go.mod
  go.sum
Labels: approved, size/M

#363 fix: add support for creating PRs from forks
  go.mod
  go.sum
  pkg/environments/fork.go
  pkg/environments/fork_test.go
  pkg/environments/gitops.go
Labels: approved, size/L

#364 fix: if no strategy is setup for staging default to auto
  go.mod
  go.sum
  pkg/promote/promote.go
  pkg/promote/promote_integration_test.go
Labels: approved, size/M

#365 chore: upgrade deps
  go.mod
  go.sum
Labels: approved, size/XS

#366 feat: use the --release option when updating helmfile
  pkg/promote/pr.go
  pkg/rules/factory/factory_test.go
  pkg/rules/factory/test_data/helmfile-release-name-option/helmfile.yaml
  pkg/rules/factory/test_data/helmfile-release-name-option/helmfile.yaml.1.expected
  pkg/rules/factory/test_data/helmfile-release-name-option/helmfile.yaml.2.expected
  pkg/rules/factory/test_data/helmfile-release-name-option/options.yaml
  pkg/rules/helmfile/helmfile_rule.go
  pkg/rules/types.go
Labels: approved, lgtm, ok-to-test, size/M

#367 chore: upgrade deps
  go.mod
  go.sum
Labels: approved, size/M
