Repository jenkins-x-plugins/jx-promote, pull requests merged in 2022-09, with the labels that each got.

#405 feat: add supply chain security
  .github/workflows/jenkins-x-release.yaml
  .github/workflows/jenkins-x/sbom-container.sh
  .github/workflows/jenkins-x/upload-binaries.sh
  .gitignore
  .goreleaser.yml
Labels: approved, size/M, ok-to-test

#407 fix: Reuse pull request
  pkg/environments/gitops.go
  pkg/environments/pr.go
  pkg/environments/types.go
  pkg/promote/pr.go
  pkg/promote/promote.go
Labels: approved, size/M

#408 refactor: upgrade go version to 1.18.6
  Makefile
  go.mod
  go.sum
  pkg/promote/promote.go
Labels: approved, size/XL
